apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  labels:
    app: tasky
spec:
  type: LoadBalancer  # Use "ClusterIP" for internal traffic only
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tasky
